### ISSUE TITLE
建议增加通配符等正则表达式支持

### ISSUE THREAD

**Issue by qfys521** [codethink-cn/Inkar-Suki#14]
如标题

**Comment by HornCopper** [comment]
通配符和正则表达式可以任选其一

**Comment by HornCopper** [comment]
实现两个还是需要不少时间的

**Comment by HornCopper** [comment]
通配符考虑使用分割，然后分段匹配？

**Comment by qfys521** [comment]
我也是这么想的，但是不知道py有没相关可以import的，，，
通过关键字符，如*,?进行分割前后？
key1+"?"+key2这样？
那如果?a?b?c怎么分割呢
滑稽.jpg

**Comment by qfys521** [comment]
况且单纯语句
你今天吃了吗?吃的如何?
这个被处理了可就太艹了

**Comment by HornCopper** [comment]
你举个例子 是什么违禁词会这样匹配

**Comment by qfys521** [comment]
比如，小明群有人打addd，我看起来不爽，而我个人习惯又喜欢直接禁止同时包含ad的字符，如果有人发一个advance，岂不是也会被禁言？

**Comment by HornCopper** [comment]
那我为什么不直接封禁addd.jpg

**Comment by qfys521** [comment]
这是栗子嘛

**Comment by HornCopper** [comment]
那你说说，你有何策略可以让对ad的封禁不牵连advance而只包括addd，正则or通配符？

**Comment by qfys521** [comment]
自己创建一种策略？
比如
"a"+"d"*3.这种(bushi)

**Comment by HornCopper** [comment]
那这不如直接封禁addd

**Comment by HornCopper** [comment]
.jpg

**Comment by qfys521** [comment]
包括包含特定码
比如UserName:HornCopper,KeyWord:\"a\"+\"d\"*3,Type:类型,UserCode:114514,GroupCode:1919810

**Comment by qfys521** [comment]
手机操作太艹了

**Comment by HornCopper** [comment]
针对特定用户的发言吗

**Comment by qfys521** [comment]
是

**Comment by HornCopper** [comment]
意义何在呢，针对别人不太好吧（

**Comment by HornCopper** [comment]
目前是这样的啊

**Comment by HornCopper** [comment]
检测所有message事件，获取文本内容，判定是否违规，执行操作（撤回&禁言）

**Comment by HornCopper** [comment]
只是还没有弄累加惩罚机制，也就是无论违规多少次都是禁言1minute

**Comment by qfys521** [comment]
而在别的群却没有必要，这样的特定

**Comment by HornCopper** [comment]
目前的确是这样啊

**Comment by qfys521** [comment]
比如说我写的代码特别好，但是我特别喜欢咕咕咕，然后完全可以在群里面添加一个针对我发言咕咕咕的消息的规则，催促我写代码(虽然但是我写的代码很淦)

**Comment by qfys521** [comment]
但是现在情况应该是所有人发言咕咕这样的消息都会被禁言。

**Comment by HornCopper** [comment]
详见Release 0.8 Changelog，已完成数据分离工作，违禁词群与群之间并不同步

**Comment by qfys521** [comment]
违禁词和用户之间呢？

**Comment by HornCopper** [comment]
也就是 加入我在a群封禁了词语word1，在b群封禁了词语word2，那么我在a群发word2，在b群发word1都**不**会被封禁

**Comment by HornCopper** [comment]
> 违禁词和用户之间呢？

违禁词目前仅与群绑定，暂不与用户绑定

**Comment by qfys521** [comment]
彳亍

**Comment by qfys521** [comment]
Close吗

**Comment by HornCopper** [comment]
有这方面需求吗，如果有的话我抽空写一个

**Comment by qfys521** [comment]
你想写其实也可以。

**Comment by qfys521** [comment]
溜了溜了hhh

**Comment by HornCopper** [comment]
如果有需求就先open，没需求你自己close吧
这里的需求是指你有无这方面的意愿，你想我当然给你写
用户说的肯定要遵守啊.png（~~开发者级用户~~）

**Comment by qfys521** [comment]
hhhc

**Comment by HornCopper** [comment]
先reopen，你认真想想再决定close或者open

**Comment by qfys521** [comment]
那就，，，

**Comment by HornCopper** [comment]
彳亍吧，那开issue干嘛的

**Comment by qfys521** [comment]
等有想法之后，我自己再open吧

**Comment by HornCopper** [comment]
OK

**Comment by qfys521** [comment]
不知道()
