### ISSUE TITLE
Unexpect `:javascript:` and "，"（U+FF0C）

### ISSUE THREAD

**Issue by MingxuanGame** [codethink-cn/Inkar-Suki#15]
https://github.com/codethink-cn/Inkar-Suki/blob/317f15751d387f30e447648caf787dcb853ff87e/initialization.py#L6

https://github.com/codethink-cn/Inkar-Suki/blob/fb8b138c87181d375e3fbeb1d8f397e3d6246147/src/plugins/register/__init__.py#L22

XD

**Comment by HornCopper** [comment]
Too old. So off topic.

**Comment by MingxuanGame** [comment]
?

**Comment by HornCopper** [comment]
就是太久远了，所以直接ot了吧（
