### ISSUE TITLE
Inkar-Suki入群后通知申请人

### ISSUE THREAD

**Issue by HornCopper** [codethink-cn/Inkar-Suki#23]
目前Inkar Suki的在线申请方式是单向的，无法将机器人是否入群告知给申请人（尽管他自己可以看到），以书面的书信形式向申请人发送一封电子邮件也许是一种礼貌的做法，是否要启用该策略呢？

**Comment by qfys521** [comment]
可以试试，但是我不太了解怎么发malil

**Comment by HornCopper** [comment]
用SMTP，但是用哪个邮箱有待商榷。

**Comment by qfys521** [comment]
bot不是有专属域名吗？

**Comment by HornCopper** [comment]
本来是inkar-suki.xyz
但是近期在更换，至inkar-suki.codethink.cn

**Comment by HornCopper** [comment]
也不是不行，上限够用吗（探头）

**Comment by qfys521** [comment]
![sogou20221111_100130790385.jpg](https://user-images.githubusercontent.com/97349476/201246013-6adc2cbc-e25e-4ecd-b9a9-ae6a7efe2fc3.jpg)

**Comment by qfys521** [comment]
我记得上限好像是2k条(?)

**Comment by HornCopper** [comment]
SMTP好麻烦啊（垂死）

**Comment by HornCopper** [comment]
👎

**Comment by HornCopper** [comment]
是这样，但是申请人的email呢，直接使用QQ邮箱吗？

**Comment by qfys521** [comment]
要不，，，你逝世手动自己搭一个邮箱服务器(?)

**Comment by qfys521** [comment]
qq邮箱我记得可以自定义用户名来着

**Comment by HornCopper** [comment]
硬件不是很支持呢

**Comment by qfys521** [comment]
就比如我
qfys520@vip.qq.com

**Comment by qfys521** [comment]
你也可以试试别的邮箱服务

**Comment by HornCopper** [comment]
问问@Chuanwise 能不能分一个出来吧。

**Comment by qfys521** [comment]
比如InKar-Suki@hotmail.com这种
?

**Comment by HornCopper** [comment]
Microsoft禁止自动化程序

**Comment by qfys521** [comment]
啊这

**Comment by qfys521** [comment]
QQ呢？

**Comment by HornCopper** [comment]
QQ也禁止

**Comment by qfys521** [comment]
copper@codethink.cn呢

**Comment by qfys521** [comment]
等会，我有点好奇

**Comment by qfys521** [comment]
为神马非得用mail

**Comment by qfys521** [comment]
我记得QQ不是有一个叫做QQ协助或者QQ咨询之类的东西吗

**Comment by qfys521** [comment]
你可以试试搞一下

**Comment by qfys521** [comment]
尝试发送，如果失败那就不管

**Comment by qfys521** [comment]
我记得没错这个默认是开的

**Comment by qfys521** [comment]
不知道还能用不能
https://wpa.qq.com/wpa_jump_page?v=3&uin=QQ号码&site=qq&menu=yes

**Comment by qfys521** [comment]
废了

**Comment by HornCopper** [comment]
思考了一下，最终策略是，停用`initialization.py`，不再使用问答式配置程序，而是用户手动填写信息，自动解析并识别。

各类的`Token`如果在问答中填写可能显得有些不自然。

**Comment by qfys521** [comment]
嗯，那这个´提议´就标记´Close´吧？
