### ISSUE TITLE
标签整理

### ISSUE THREAD

**Issue by qfys521** [codethink-cn/Inkar-Suki#24]
申请整理标签

**Comment by HornCopper** [comment]
你有admin权限直接改就行吧（

**Comment by qfys521** [comment]
整理完成![Screenshot_2022-11-17-22-52-08-055_com.chrome.beta.jpg](https://user-images.githubusercontent.com/97349476/202479478-5eee0476-0ef8-4d72-b99a-4c0e7c01d4e3.jpg)
