### ISSUE TITLE
使用申请

### ISSUE THREAD

**Issue by 619cp** [codethink-cn/Inkar-Suki#449]
申请人QQ：1191176262
申请群聊：475610303
群聊请求数据如下：{"group_create_time": 0, "group_id": 648928221, "group_level": 0, "group_memo": "", "group_name": "十年一梦.", "max_member_count": 0, "member_count": 0}

**Comment by HornCopper** [comment]
推荐你去用户群而不是这里申请，我们的申请策略已经更改
