### ISSUE TITLE
使用申请

### ISSUE THREAD

**Issue by lcy124** [codethink-cn/Inkar-Suki#453]
申请人QQ：3389476391
申请群聊：306543151
群聊请求数据如下：{"group_create_time": 0, "group_id": 306543151, "group_level": 0, "group_memo": "", "group_name": "［甜椒］周4打周4的车", "max_member_count": 0, "member_count": 0}

**Comment by HornCopper** [comment]
请不要使用issue进行申请，私聊用户群的群主即可
