### ISSUE TITLE
绑定服务器失败

### ISSUE THREAD

**Issue by ZhengYue95** [codethink-cn/Inkar-Suki#456]
#### Other relevant information（格外信息）
- 你的群号:446346185
- 机器人版本:10

**Comment by ZhengYue95** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Desktop\\Inkar-Suki/src/tools/permission.json'

**Comment by ZhengYue95** [comment]
08-27 15:50:59 [ERROR] nonebot | Running matcher <Matcher from src.plugins.banword, type=message, priority=3, temp=False> failed.
Traceback (most recent call last):

**Comment by HornCopper** [comment]
请参考文档第二版的`FAQ`章节。

[传送门](https://inkar-suki.codethink.cn/docs2/#/faq?id=permissionjson%e7%b3%bb%e5%88%97%e9%97%ae%e9%a2%98)

**Comment by HornCopper** [comment]
如果解决，请关闭该`issue`，反之，欢迎继续提问。
