### ISSUE TITLE
机器人初次入群的bug

### ISSUE THREAD

**Issue by root13920** [codethink-cn/Inkar-Suki#810]
#### Steps to reproduce（问题复现步骤）

在自建机器人新拉入群聊时 由于src/data/中未生成该群的配置文件 会导致出现以下问题
![image](https://github.com/user-attachments/assets/43f11dcb-5cf2-4e52-90ef-7c79f30f927a)
查看代码发现是由于src/tools/basic/message_process.py文件中的getGroupData()函数 在处理群聊信息时会直接去访问src/data/群号/settings.json文件  由于在初次进群没有生成对应的文件  导致后续数据处理中返回了空值
![image](https://github.com/user-attachments/assets/f0e1c3e3-5135-4a20-9b19-85135b8900ca)

导致在97行处获取不到subscribe参数出现报错
![image](https://github.com/user-attachments/assets/211a4554-21a5-4197-ae2a-40877d592af9)

#### Other relevant information（格外信息）
- 你的群号:
- 机器人版本:fcba16b465353a6882a08072fca9ce11f70a46cc

**Comment by HornCopper** [comment]
尝试使用重置音卡？由于文件io性能开销过大我才移除的那一段代码，如有需要可以自行添加
