### ISSUE TITLE
Inkar-Suki·使用申请

### ISSUE THREAD

**Issue by Venter1228** [codethink-cn/Inkar-Suki#83]
申请人QQ：248891228
申请群聊：242128726
群聊请求数据如下：{"group_create_time": 0, "group_id": 242128726, "group_level": 0, "group_memo": "-", "group_name": "我们的窝", "max_member_count": 0, "member_count": 0}

**Comment by HornCopper** [comment]
如果是音卡实例访问，用户名有误；
如果是用户提出申请，不应该有群聊请求数据
